sudo: required
services:
  - docker

before_install:
  - docker build -t anuchatk/multi-docker-aws -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anuchatk/multi-docker-aws npm run test -- --coverage

after_success:
  - docker build -t anuchatk/multi-client- ./client
  - docker build -t anuchatk/multi-nginx ./nginx
  - docker build -t anuchatk/multi-server ./server
  - docker build -t anuchatk/multi-worker ./worker
  # Login ot the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those image and push them to docker hub
  - docker push anuchatk/multi-client
  - docker push anuchatk/multi-nginx
  - docker push anuchatk/multi-server
  - docker push anuchatk/multi-worker
